FROM ubuntu:22.04

WORKDIR /app

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/Symph0nia/CyberEdge/releases/download/v1.0.1/cyberedge-linux-amd64 -O cyberedge
RUN chmod +x cyberedge

EXPOSE 31337

CMD ["./cyberedge"]