FROM nginx:alpine

RUN apk add --no-cache wget unzip

# 添加 -o 参数来强制覆盖
RUN wget https://github.com/Symph0nia/CyberEdge-Front/releases/download/v1.0.5/cyberedge-front.zip -O /tmp/frontend.zip && \
    unzip -o /tmp/frontend.zip -d /usr/share/nginx/html/ && \
    rm /tmp/frontend.zip

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 47808