version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "31337:31337"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_ADDR=redis:6379
    volumes:
      - ./.env:/app/.env
    depends_on:
      - mongodb
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "47808:47808"
    depends_on:
      - backend

volumes:
  mongodb_data:
  redis_data: