version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "31337:31337"
    environment:
      - REDIS_ADDR=redis:6379
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "47808:47808"
    depends_on:
      - backend

volumes:
  redis_data: